/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingsimulator.Views;

import java.awt.Color;

/**
 *
 * @author Amar
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        HeaderText = new javax.swing.JLabel();
        jpanComponent = new javax.swing.JPanel();
        ParkingMesto1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPlati1 = new javax.swing.JButton();
        lblVreme1 = new javax.swing.JLabel();
        ParkingMesto2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPlati2 = new javax.swing.JButton();
        lblVreme2 = new javax.swing.JLabel();
        ParkingMesto3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnPlati3 = new javax.swing.JButton();
        lblVreme3 = new javax.swing.JLabel();
        ParkingMesto4 = new javax.swing.JPanel();
        btnPlati4 = new javax.swing.JButton();
        lblVreme4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlTabla = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        lblBrMesta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRadnoVreme = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnDnevniIzvestaj = new javax.swing.JButton();
        btnOdjava = new javax.swing.JButton();
        btnIzmenaCene = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground.setMaximumSize(new java.awt.Dimension(840, 498));
        pnlBackground.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground.setPreferredSize(new java.awt.Dimension(840, 498));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(0, 71, 126));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderText.setBackground(new java.awt.Color(255, 255, 255));
        HeaderText.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        HeaderText.setForeground(new java.awt.Color(255, 255, 255));
        HeaderText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeaderText.setText("ParkingSimulator");
        pnlHeader.add(HeaderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        pnlBackground.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 600, 50));

        jpanComponent.setBackground(new java.awt.Color(195, 195, 195));
        jpanComponent.setMinimumSize(new java.awt.Dimension(600, 390));
        jpanComponent.setPreferredSize(new java.awt.Dimension(630, 470));
        jpanComponent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParkingMesto1.setBackground(new java.awt.Color(255, 51, 51));
        ParkingMesto1.setMaximumSize(new java.awt.Dimension(200, 150));
        ParkingMesto1.setMinimumSize(new java.awt.Dimension(200, 150));
        ParkingMesto1.setPreferredSize(new java.awt.Dimension(200, 150));
        ParkingMesto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        ParkingMesto1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, -1));

        btnPlati1.setBackground(new java.awt.Color(204, 204, 204));
        btnPlati1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnPlati1.setText("Plati");
        btnPlati1.setFocusPainted(false);
        btnPlati1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlati1ActionPerformed(evt);
            }
        });
        ParkingMesto1.add(btnPlati1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        lblVreme1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVreme1.setForeground(new java.awt.Color(255, 255, 255));
        lblVreme1.setText("Vreme 1");
        ParkingMesto1.add(lblVreme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 80, 30));

        jpanComponent.add(ParkingMesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 275, 175));

        ParkingMesto2.setBackground(new java.awt.Color(255, 204, 51));
        ParkingMesto2.setMaximumSize(new java.awt.Dimension(200, 150));
        ParkingMesto2.setMinimumSize(new java.awt.Dimension(200, 150));
        ParkingMesto2.setPreferredSize(new java.awt.Dimension(200, 150));
        ParkingMesto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("2");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 50));
        ParkingMesto2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 30, -1));

        btnPlati2.setBackground(new java.awt.Color(204, 204, 204));
        btnPlati2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnPlati2.setText("Plati");
        btnPlati2.setFocusPainted(false);
        btnPlati2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlati2ActionPerformed(evt);
            }
        });
        ParkingMesto2.add(btnPlati2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        lblVreme2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVreme2.setForeground(new java.awt.Color(255, 255, 255));
        lblVreme2.setText("Vreme 2");
        ParkingMesto2.add(lblVreme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 80, 27));

        jpanComponent.add(ParkingMesto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 275, 175));

        ParkingMesto3.setBackground(new java.awt.Color(0, 153, 0));
        ParkingMesto3.setMaximumSize(new java.awt.Dimension(200, 150));
        ParkingMesto3.setMinimumSize(new java.awt.Dimension(200, 150));
        ParkingMesto3.setPreferredSize(new java.awt.Dimension(200, 150));
        ParkingMesto3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("3");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 50));
        ParkingMesto3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 30, 40));

        btnPlati3.setBackground(new java.awt.Color(204, 204, 204));
        btnPlati3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnPlati3.setText("Plati");
        btnPlati3.setFocusPainted(false);
        btnPlati3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlati3ActionPerformed(evt);
            }
        });
        ParkingMesto3.add(btnPlati3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        lblVreme3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVreme3.setForeground(new java.awt.Color(255, 255, 255));
        lblVreme3.setText("Vreme 3");
        ParkingMesto3.add(lblVreme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 80, 27));

        jpanComponent.add(ParkingMesto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 275, 275, 175));

        ParkingMesto4.setBackground(new java.awt.Color(0, 0, 204));
        ParkingMesto4.setMaximumSize(new java.awt.Dimension(200, 150));
        ParkingMesto4.setMinimumSize(new java.awt.Dimension(200, 150));
        ParkingMesto4.setPreferredSize(new java.awt.Dimension(200, 150));
        ParkingMesto4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlati4.setBackground(new java.awt.Color(204, 204, 204));
        btnPlati4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnPlati4.setText("Plati");
        btnPlati4.setFocusPainted(false);
        btnPlati4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlati4ActionPerformed(evt);
            }
        });
        ParkingMesto4.add(btnPlati4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        lblVreme4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblVreme4.setForeground(new java.awt.Color(255, 255, 255));
        lblVreme4.setText("Vreme 4");
        ParkingMesto4.add(lblVreme4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 80, 27));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("4");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        ParkingMesto4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 30, 50));

        jpanComponent.add(ParkingMesto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 275, 275, 175));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingsimulator/Views/Slike/Untitled.png"))); // NOI18N
        jpanComponent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 600, 90));

        pnlBackground.add(jpanComponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 600, 450));

        pnlTabla.setBackground(new java.awt.Color(51, 102, 255));
        pnlTabla.setMinimumSize(new java.awt.Dimension(240, 180));
        pnlTabla.setPreferredSize(new java.awt.Dimension(240, 180));
        pnlTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 102, 102));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tabla");
        pnlTabla.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));
        pnlTabla.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 10));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Broj slobodnih mesta:");
        pnlTabla.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 20));

        lblBrMesta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblBrMesta.setForeground(new java.awt.Color(255, 255, 255));
        lblBrMesta.setText("Get br mesta");
        pnlTabla.add(lblBrMesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, 20));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Radno vreme:");
        pnlTabla.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 90, 20));

        lblRadnoVreme.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblRadnoVreme.setForeground(new java.awt.Color(255, 255, 255));
        lblRadnoVreme.setText("get Radnog ");
        pnlTabla.add(lblRadnoVreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 20));
        pnlTabla.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 10));

        btnDnevniIzvestaj.setBackground(new java.awt.Color(51, 102, 255));
        btnDnevniIzvestaj.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnDnevniIzvestaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDnevniIzvestaj.setText("Dnevni izveštaj");
        btnDnevniIzvestaj.setBorderPainted(false);
        btnDnevniIzvestaj.setFocusPainted(false);
        btnDnevniIzvestaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDnevniIzvestajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDnevniIzvestajMouseExited(evt);
            }
        });
        btnDnevniIzvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDnevniIzvestajActionPerformed(evt);
            }
        });
        pnlTabla.add(btnDnevniIzvestaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 30));

        btnOdjava.setBackground(new java.awt.Color(51, 102, 255));
        btnOdjava.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnOdjava.setForeground(new java.awt.Color(255, 255, 255));
        btnOdjava.setText("Odjava");
        btnOdjava.setBorderPainted(false);
        btnOdjava.setFocusPainted(false);
        btnOdjava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOdjavaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOdjavaMouseExited(evt);
            }
        });
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });
        pnlTabla.add(btnOdjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnIzmenaCene.setBackground(new java.awt.Color(51, 102, 255));
        btnIzmenaCene.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnIzmenaCene.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmenaCene.setText("Izmena cene");
        btnIzmenaCene.setBorderPainted(false);
        btnIzmenaCene.setFocusPainted(false);
        btnIzmenaCene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIzmenaCeneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIzmenaCeneMouseExited(evt);
            }
        });
        pnlTabla.add(btnIzmenaCene, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 30));

        pnlBackground.add(pnlTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlati1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlati1ActionPerformed
       
    }//GEN-LAST:event_btnPlati1ActionPerformed

    private void btnPlati2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlati2ActionPerformed
        
    }//GEN-LAST:event_btnPlati2ActionPerformed

    private void btnPlati3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlati3ActionPerformed
        
    }//GEN-LAST:event_btnPlati3ActionPerformed

    private void btnPlati4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlati4ActionPerformed

    }//GEN-LAST:event_btnPlati4ActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        // TODO add your handling code here:
       
        MainFrame mf=new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void btnDnevniIzvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDnevniIzvestajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDnevniIzvestajActionPerformed

    private void btnDnevniIzvestajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDnevniIzvestajMouseEntered
        // TODO add your handling code here:
        this.btnDnevniIzvestaj.setBackground(Color.decode("#00477E"));
    this.btnDnevniIzvestaj.setForeground(Color.white);
    }//GEN-LAST:event_btnDnevniIzvestajMouseEntered

    private void btnDnevniIzvestajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDnevniIzvestajMouseExited
        // TODO add your handling code here:
        this.btnDnevniIzvestaj.setBackground(Color.decode("#3366FF"));
    this.btnDnevniIzvestaj.setForeground(Color.white);
    }//GEN-LAST:event_btnDnevniIzvestajMouseExited

    private void btnIzmenaCeneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzmenaCeneMouseEntered
        this.btnIzmenaCene.setBackground(Color.decode("#00477E"));
    this.btnIzmenaCene.setForeground(Color.white);
    }//GEN-LAST:event_btnIzmenaCeneMouseEntered

    private void btnIzmenaCeneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzmenaCeneMouseExited
        // TODO add your handling code here:
        this.btnIzmenaCene.setBackground(Color.decode("#3366FF"));
    this.btnIzmenaCene.setForeground(Color.white);
    }//GEN-LAST:event_btnIzmenaCeneMouseExited

    private void btnOdjavaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdjavaMouseEntered
        // TODO add your handling code here:
        this.btnOdjava.setBackground(Color.decode("#00477E"));
    this.btnOdjava.setForeground(Color.white);
    }//GEN-LAST:event_btnOdjavaMouseEntered

    private void btnOdjavaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOdjavaMouseExited
        // TODO add your handling code here:
        this.btnOdjava.setBackground(Color.decode("#3366FF"));
    this.btnOdjava.setForeground(Color.white);
    }//GEN-LAST:event_btnOdjavaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeaderText;
    private javax.swing.JPanel ParkingMesto1;
    private javax.swing.JPanel ParkingMesto2;
    private javax.swing.JPanel ParkingMesto3;
    private javax.swing.JPanel ParkingMesto4;
    private javax.swing.JButton btnDnevniIzvestaj;
    private javax.swing.JButton btnIzmenaCene;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnPlati1;
    private javax.swing.JButton btnPlati2;
    private javax.swing.JButton btnPlati3;
    private javax.swing.JButton btnPlati4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel jpanComponent;
    private javax.swing.JLabel lblBrMesta;
    private javax.swing.JLabel lblRadnoVreme;
    private javax.swing.JLabel lblVreme1;
    private javax.swing.JLabel lblVreme2;
    private javax.swing.JLabel lblVreme3;
    private javax.swing.JLabel lblVreme4;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlTabla;
    // End of variables declaration//GEN-END:variables
}
