/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingsimulator.Views;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import parkingsimulator.Models.DBController;

/**
 *
 * @author Amar
 */
public class PlatiFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form Plati
     */
    private ArrayList<String> poruke;
    private ArrayList<StringBuffer> boje;
    private JPanel panelKojiMenjam;
    private int redniBroj;
    float naplatnaCena;
    public PlatiFrame(){initComponents();}
    public PlatiFrame(ArrayList<String> poruke1,ArrayList<StringBuffer> boje1,JPanel panelKojiMenjam1,int redniBroj,ArrayList<StringBuffer> ids1) {
        initComponents();
        Random r=new Random();  
        this.lblIDVozila2.setText(ids1.get(redniBroj).toString()); // Saljemo kad se zauzme mesto
        this.slldCena.setValue(1);
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.poruke=poruke1;
        this.boje=boje1;
        this.panelKojiMenjam=panelKojiMenjam1;
        this.redniBroj=redniBroj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPlati = new javax.swing.JPanel();
        slldCena = new javax.swing.JSlider();
        lblIDVozila = new javax.swing.JLabel();
        lblIDVozila2 = new javax.swing.JLabel();
        btnUplati = new javax.swing.JButton();
        lblCena = new javax.swing.JLabel();
        lblCena2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlPlati.setBackground(new java.awt.Color(0, 40, 43));
        pnlPlati.setForeground(new java.awt.Color(248, 193, 30));
        pnlPlati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slldCena.setBackground(new java.awt.Color(248, 193, 30));
        slldCena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        slldCena.setForeground(new java.awt.Color(0, 40, 43));
        slldCena.setMajorTickSpacing(1);
        slldCena.setMaximum(14);
        slldCena.setMinimum(1);
        slldCena.setPaintLabels(true);
        slldCena.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slldCenaStateChanged(evt);
            }
        });
        pnlPlati.add(slldCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 105, 266, -1));

        lblIDVozila.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblIDVozila.setForeground(new java.awt.Color(248, 193, 30));
        lblIDVozila.setText("ID vozila:");
        pnlPlati.add(lblIDVozila, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 27));

        lblIDVozila2.setBackground(new java.awt.Color(0, 40, 43));
        lblIDVozila2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblIDVozila2.setForeground(new java.awt.Color(248, 193, 30));
        pnlPlati.add(lblIDVozila2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 11, 68, 27));

        btnUplati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkingsimulator/Views/Slike/btnUplati.png"))); // NOI18N
        btnUplati.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 193, 30)));
        btnUplati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplatiActionPerformed(evt);
            }
        });
        pnlPlati.add(btnUplati, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 229, -1, 33));

        lblCena.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCena.setForeground(new java.awt.Color(248, 193, 30));
        lblCena.setText("Vreme zadrzavanja:");
        pnlPlati.add(lblCena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, 27));

        lblCena2.setForeground(new java.awt.Color(248, 193, 30));
        pnlPlati.add(lblCena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 77, 27));

        jSeparator1.setBackground(new java.awt.Color(248, 193, 30));
        pnlPlati.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 10));

        jSeparator2.setBackground(new java.awt.Color(248, 193, 30));
        pnlPlati.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPlati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        evt.getWindow().setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void slldCenaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slldCenaStateChanged
        try {
            // TODO add your handling code here:
            lblCena2.setText(String.valueOf(this.slldCena.getValue()*(DBController.require().getCena()))+"din");
            naplatnaCena=this.slldCena.getValue()*(DBController.require().getCena());
        } catch (SQLException ex) {
            Logger.getLogger(PlatiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_slldCenaStateChanged

    private void btnUplatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplatiActionPerformed
        String idvozila=lblIDVozila2.getText();
        if(poruke.get(redniBroj).charAt(1)=='D' && poruke.get(redniBroj).charAt(2)=='A'){
            try {
                DBController.require().setParkirani(idvozila , naplatnaCena);
            } catch (SQLException ex) {
                Logger.getLogger(PlatiFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.boje.get(redniBroj).replace(0, boje.get(redniBroj).length(), "r");
            //panelKojiMenjam.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Uspesno ste uplatili!");
            this.setVisible(false);
            this.dispose();
    }//GEN-LAST:event_btnUplatiActionPerformed

    }
    
        

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlatiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUplati;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCena;
    private javax.swing.JLabel lblCena2;
    private javax.swing.JLabel lblIDVozila;
    private javax.swing.JLabel lblIDVozila2;
    private javax.swing.JPanel pnlPlati;
    private javax.swing.JSlider slldCena;
    // End of variables declaration//GEN-END:variables
}
